name: Build and Lint
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  build-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false
          submodules: recursive
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          standalone: false
      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm lint