name: Build and Lint

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-lint:
    name: Build and Lint

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3 # 最新版に更新
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@latest
        with:
          version: '9.11.0'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm lint